# This appveyor.yml is based on LOOT's appveyor.yml:
# https://github.com/loot/loot/blob/dev/appveyor.yml

os: Visual Studio 2015

version: "{build}-{branch}"

clone_depth: 50
configuration: Release

cache:
    - C:\.hunter

before_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - ps: mkdir build
    - cd build
    - cmake --version
    - cmake ..\src -G "Visual Studio 14 2015" -DSTRIDE_BOOST_HUNTER=ON

# build:
#     verbosity: minimal
#     project: '$(APPVEYOR_BUILD_FOLDER)\build\STRIDE.sln'

build_script:
    - echo "Build has been disabled"
