# This appveyor.yml is based on LOOT's appveyor.yml:
# https://github.com/loot/loot/blob/dev/appveyor.yml

os: Visual Studio 2015

version: "{build}-{branch}"

clone_depth: 50
configuration: Release

cache:
    - C:\projects\boost_1_61_0\boost
    - C:\projects\boost_1_61_0\stage\32\lib

install:
    - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.1.0/install_boost.py', "$env:APPVEYOR_BUILD_FOLDER\install_boost.py")
    - ps: python $env:APPVEYOR_BUILD_FOLDER\install_boost.py -d C:\projects -b 1.61.0 -a 32 date_time filesystem system thread

before_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - ps: mkdir build
    - cd build
    - cmake --version
    - cmake ..\src -G "Visual Studio 14 2015" -DSTRIDE_BOOST_ROOT="C:\projects\boost_1_61_0" -DBOOST_LIBRARYDIR="C:\projects\boost_1_61_0\stage\32\lib"

# build:
#     verbosity: minimal
#     project: '$(APPVEYOR_BUILD_FOLDER)\build\STRIDE.sln'
build: off